### PR TITLE
Validate config and workspaces on load from file

### LINKED ISSUE #19: [BUG]: Bad argument to ipairs
# Reproduction

1. Install projections
2. Setup the first recommended recipe. Bind <leader>pp to run `Telescope projections` (see below)
3. Restart neovim (I'm using Neovide), and open a project by pressing `<leader>pp`
4. Select a project
5. Open a new tab `:tabe`
6. Press `<leader>pp` again

## Expected

The project selector Telescope UI renders allowing me to select a project.

## Actual

When pressing `<leader>pp` it throws the following error, preventing the telescope UI from rendering:

```
E5108: Error executing lua: Vim:Error executing Lua callback: ...acker/opt/projections.nvim/lua/projections/workspace.lua:84: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
	[C]: in function 'ipairs'
	...acker/opt/projections.nvim/lua/projections/workspace.lua:84: in function 'is_project'
	...acker/opt/projections.nvim/lua/projections/workspace.lua:56: in function 'projects'
	...ojections.nvim/lua/telescope/_extensions/projections.lua:13: in function 'project_finder'
	...ojections.nvim/lua/telescope/_extensions/projections.lua:41: in function <...ojections.nvim/lua/telescope/_extensions/projections.lua:36>
	...pack/packer/opt/telescope.nvim/lua/telescope/command.lua:193: in function 'run_command'
	...pack/packer/opt/telescope.nvim/lua/telescope/command.lua:253: in function 'load_command'
	...site/pack/packer/opt/telescope.nvim/plugin/telescope.lua:108: in function <...site/pack/packer/opt/telescope.nvim/plugin/telescope.lua:107>
	[C]: at 0x01059656e6
stack traceback:
	[C]: at 0x01059656e6
```

This plugin seems super helpful, please let me know if any more info would help for debugging.

### Recipe Used

```lua
use({
    "gnikdroy/projections.nvim",
    config = function()
        require("projections").setup({})

        -- Bind <leader>fp to Telescope projections
        require('telescope').load_extension('projections')
        vim.keymap.set("n", "<leader>pp", function() vim.cmd("Telescope projections") end)

        -- Autostore session on VimExit
        local Session = require("projections.session")
        vim.api.nvim_create_autocmd({ 'VimLeavePre' }, {
            callback = function() Session.store(vim.loop.cwd()) end,
        })

        -- Switch to project if vim was started in a project dir
        local switcher = require("projections.switcher")
        vim.api.nvim_create_autocmd({ "VimEnter" }, {
            callback = function()
                if vim.fn.argc() == 0 then switcher.switch(vim.loop.cwd()) end
            end,
        })
    end
})
```

### PR DESCRIPTION
**Pull request by eccentric-j**
Fixes #19 

Validates config on setup and workspaces after deserializing when reading from file.

### CODE REVIEW

**Comment by GnikDroy** [comment]
Great work!

I've added some additional validation and moved everything to `validators.lua`. Will merge after some additional testing.

**Comment by eccentric-j** [comment]
Those changes look good. Thinking on it, would it be beneficial to refactor those ifs into assertString and assertTable? 

In theory would make those validations less boilerplatey, less repetition in the error message formatting, composable for other parts of the plug-in if desired.

Happy to give it a shot if interested.

**Comment by GnikDroy** [comment]
@eccentric-j Yes, that sounds great. I will wait for your commits then.

**Comment by eccentric-j** [comment]
Finished. Seems to have made the actual validate functions quite a bit cleaner. Let me know what you think!

**Comment by GnikDroy** [comment]
I think `assert_string`, `assert_table`, and `assert_function` look strikingly similar 😂. The same goes for `assert_optional_*` group of functions. I think they can be converted into `assert_X` and `assert_optional_X` or something. No worries though, I will fix this.

**Comment by eccentric-j** [comment]
> I think `assert_string`, `assert_table`, and `assert_function` look strikingly similar 😂. The same goes for `assert_optional_*` group of functions. I think they can be converted into `assert_X` and `assert_optional_X` or something. No worries though, I will fix this.

That's true. I did consider that, but I've also shot myself in the foot coupling things together too much in the spirit of DRY. If one of those does need to work differently later, it's really easy to change without affecting the others. That said, do what you feel is best 🙂

**Comment by GnikDroy** [comment]
@eccentric-j I have combined all the `assert_*`, and `assert_optional_*` functions into `assert_type`. I think this works. Doesn't look too coupled for now. Also, allowed me to replace the final error() line with an `assert_type`.

The only thing is you cannot distinguish "list like table" with "map like table". I was planning on adding that to the `assert_type` function as well. But it seems like there is no reliable way to differentiate the two in lua in the first place. So, we can't reliably check that.

If everything looks fine, I will merge after some testing.

**Pull request merged**
